password/urls.py
from django.urls import path

from . import views

app_name = 'password'

urlpatterns = [
	# Template
	path('generator/', views.password_generator, name="password_generator"),
]

project5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vault/', include("vault.urls")),
    path('password/', include("password.urls")),
    path('', include("users.urls")),
]

# If the project is on development environment, the static files will be placed on another directory
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
	path('', views.AccountView.as_view(), name="account"),
	path('sign-up', views.SignUpView.as_view(), name="sign-up"),
	path('sign-in', views.SignInView.as_view(), name="sign-in"),
	path('sign-out', views.sign_out, name="sign-out"),
]

vault/urls.py
from django.urls import path

from . import views

app_name = 'vault'

urlpatterns = [
	# Template
	path('', views.AllItemsView.as_view(), name="all-items"),
	path('passwords', views.PasswordsView.as_view(), name="passwords"),
	path('notes', views.NotesView.as_view(), name="notes"),
	path('addresses', views.AddressesView.as_view(), name="addresses"),
	path('payment-cards', views.PaymentCardsView.as_view(), name="payment-cards"),
	path('bank-accounts', views.BankAccountsView.as_view(), name="bank-accounts"),

	# Create
	path('create/password', views.CreatePasswordView.as_view(), name="create_password"),
	path('create/note', views.CreateNoteView.as_view(), name="create_note"),
	path('create/address', views.CreateAddressView.as_view(), name="create_address"),
	path('create/payment-card', views.CreatePaymentCardView.as_view(), name="create_payment_card"),
	path('create/bank-account', views.CreateBankAccountView.as_view(), name="create_bank_account"),

	# Detail
	path('detail/password/<pk>', views.DetailPasswordView.as_view(), name="detail_password"),
	path('detail/note/<pk>', views.DetailNoteView.as_view(), name="detail_note"),
	path('detail/address/<pk>', views.DetailAddressView.as_view(), name="detail_address"),
	path('detail/payment_card/<pk>', views.DetailPaymentCardView.as_view(), name="detail_payment_card"),
	path('detail/bank_account/<pk>', views.DetailBankAccountView.as_view(), name="detail_bank_account"),

	# Update
	path('update/password/<int:pk>', views.UpdatePasswordView.as_view(), name="update_password"),
	path('update/note/<int:pk>', views.UpdateNoteView.as_view(), name="update_note"),
	path('update/address/<int:pk>', views.UpdateAddressView.as_view(), name="update_address"),
	path('update/payment_card/<int:pk>', views.UpdatePaymentCardView.as_view(), name="update_payment_card"),
	path('update/bank_account/<int:pk>', views.UpdateBankAccountView.as_view(), name="update_bank_account"),

	# Delete
	path('delete/password/<int:pk>', views.DeletePasswordView.as_view(), name="delete_password"),
	path('delete/note/<int:pk>', views.DeleteNoteView.as_view(), name="delete_note"),
	path('delete/address/<int:pk>', views.DeleteAddressView.as_view(), name="delete_address"),
	path('delete/payment_card/<int:pk>', views.DeletePaymentCardView.as_view(), name="delete_payment_card"),
	path('delete/bank_account/<int:pk>', views.DeleteBankAccountView.as_view(), name="delete_bank_account"),
]

templates/partials/nav.html
{% if request.user.is_authenticated %}
<ul class="sidenav">
  {% if request.path == "/" %}
  <li><a class="active" href="{% url 'users:account' %}">User Account</a></li>
  {% else %}
  <li><a href="{% url 'users:account' %}">User Account</a></li>
  {% endif %}

  {% if request.path == "/password/" %}
  <li><a class="active" href="{% url 'password:password_generator' %}">Password generator</a></li>
  {% else %}
  <li><a href="{% url 'password:password_generator' %}">Password generator</a></li>
  {% endif %}

  {% if request.path == "/vault/" %}
  <li><a class="active" href="{% url 'vault:all-items' %}">All Items</a></li>
  {% else %}
  <li><a href="{% url 'vault:all-items' %}">All Items</a></li>
  {% endif %}

  {% if request.path == "/vault/passwords" %}
  <li><a class="active" href="{% url 'vault:passwords' %}">Passwords</a></li>
  {% else %}
  <li><a href="{% url 'vault:passwords' %}">Passwords</a></li>
  {% endif %}

  {% if request.path == "/vault/notes" %}
  <li><a class="active" href="{% url 'vault:notes' %}">Notes</a></li>
  {% else %}
  <li><a href="{% url 'vault:notes' %}">Notes</a></li>
  {% endif %}

  {% if request.path == "/vault/addresses" %}
  <li><a class="active" href="{% url 'vault:addresses' %}">Addresses</a></li>
  {% else %}
  <li><a href="{% url 'vault:addresses' %}">Addresses</a></li>
  {% endif %}

  {% if request.path == "/vault/payment-cards" %}
  <li><a class="active" href="{% url 'vault:payment-cards' %}">Payment Cards</a></li>
  {% else %}
  <li><a href="{% url 'vault:payment-cards' %}">Payment Cards</a></li>
  {% endif %}

  {% if request.path == "/vault/bank-accounts" %}
  <li><a class="active" href="{% url 'vault:bank-accounts' %}">Bank Accounts</a></li>
  {% else %}
  <li><a href="{% url 'vault:bank-accounts' %}">Bank Accounts</a></li>
  {% endif %}

  {% if "sign-out" in request.path %}
  <li><a class="active" href="{% url 'users:sign-out' %}">Sign Out</a></li>
  {% else %}
  <li><a href="{% url 'users:sign-out' %}">Sign Out</a></li>
  {% endif %}
  
</ul>
{% else %}
<ul class="sidenav">

  {% if "sign-in" in request.path %}
  <li><a class="active" href="{% url 'users:sign-in' %}">Sign In</a></li>
  {% else %}
  <li><a href="{% url 'users:sign-in' %}">Sign In</a></li>
  {% endif %}
  
  {% if "sign-up" in request.path %}
  <li><a class="active" href="{% url 'users:sign-up' %}">Sign Up</a></li>
  {% else %}
  <li><a href="{% url 'users:sign-up' %}">Sign Up</a></li>
  {% endif %}
</ul>
{% endif %}