password/urls.py
from django.urls import path

from . import views

app_name = 'password'

urlpatterns = [
	# Template
	path('generator/', views.password_generator, name="password_generator"),
]

project5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vault/', include("vault.urls")),
    path('password/', include("password.urls")),
    path('', include("users.urls")),
]

# If the project is on development environment, the static files will be placed on another directory
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
	path('', views.AccountView.as_view(), name="account"),
	path('sign-up', views.SignUpView.as_view(), name="sign-up"),
	path('sign-in', views.SignInView.as_view(), name="sign-in"),
	path('sign-out', views.sign_out, name="sign-out"),
]

vault/urls.py
from django.urls import path

from . import views

app_name = 'vault'

urlpatterns = [
	# Template
	path('', views.AllItemsView.as_view(), name="all-items"),
	path('passwords', views.PasswordsView.as_view(), name="passwords"),
	path('notes', views.NotesView.as_view(), name="notes"),
	path('addresses', views.AddressesView.as_view(), name="addresses"),
	path('payment-cards', views.PaymentCardsView.as_view(), name="payment-cards"),
	path('bank-accounts', views.BankAccountsView.as_view(), name="bank-accounts"),

	# Create
	path('create/password', views.CreatePasswordView.as_view(), name="create_password"),
	path('create/note', views.CreateNoteView.as_view(), name="create_note"),
	path('create/address', views.CreateAddressView.as_view(), name="create_address"),
	path('create/payment-card', views.CreatePaymentCardView.as_view(), name="create_payment_card"),
	path('create/bank-account', views.CreateBankAccountView.as_view(), name="create_bank_account"),

	# Detail
	path('detail/password/<pk>', views.DetailPasswordView.as_view(), name="detail_password"),
	path('detail/note/<pk>', views.DetailNoteView.as_view(), name="detail_note"),
	path('detail/address/<pk>', views.DetailAddressView.as_view(), name="detail_address"),
	path('detail/payment_card/<pk>', views.DetailPaymentCardView.as_view(), name="detail_payment_card"),
	path('detail/bank_account/<pk>', views.DetailBankAccountView.as_view(), name="detail_bank_account"),

	# Update
	path('update/password/<int:pk>', views.UpdatePasswordView.as_view(), name="update_password"),
	path('update/note/<int:pk>', views.UpdateNoteView.as_view(), name="update_note"),
	path('update/address/<int:pk>', views.UpdateAddressView.as_view(), name="update_address"),
	path('update/payment_card/<int:pk>', views.UpdatePaymentCardView.as_view(), name="update_payment_card"),
	path('update/bank_account/<int:pk>', views.UpdateBankAccountView.as_view(), name="update_bank_account"),

	# Delete
	path('delete/password/<int:pk>', views.DeletePasswordView.as_view(), name="delete_password"),
	path('delete/note/<int:pk>', views.DeleteNoteView.as_view(), name="delete_note"),
	path('delete/address/<int:pk>', views.DeleteAddressView.as_view(), name="delete_address"),
	path('delete/payment_card/<int:pk>', views.DeletePaymentCardView.as_view(), name="delete_payment_card"),
	path('delete/bank_account/<int:pk>', views.DeleteBankAccountView.as_view(), name="delete_bank_account"),
]

password/models.py
from django.db import models

# Create your models here.

password/views.py
import json

from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from .utils import generate_secure_password

# Create your views here.
@csrf_exempt
def password_generator(request):

    context = {}
    
    if request.method == "POST":

        # Get data from form
        lower = request.POST.get("lower")
        upper = request.POST.get("upper")
        numbers = request.POST.get("numbers")
        symbols = request.POST.get("symbols")
        length = request.POST.get("length")

        if(lower == upper == numbers == symbols == length == None):

            data = json.loads(request.body)

            lower = data.get("lower")
            upper = data.get("upper")
            numbers = data.get("numbers")
            symbols = data.get("symbols")
            length = data.get("length")

        print("Hola Mundo: ", lower, upper, numbers, symbols, length)
        
        # Generates a secure password
        password = generate_secure_password(lower, upper, numbers, symbols, length)
        
        data = {'result': 'Success', 'message': 'Password generated successfully', 'password': password}
        return JsonResponse(data)

    elif request.method != "GET":
        context["error"] = "Request method should be POST or GET."
    
    return render(request, "password/generate_password.html", context)

vault/views.py
from django.shortcuts import redirect, reverse, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.conf import settings
from django.http import JsonResponse
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from project5.mixins import AjaxFormMixin, is_ajax

from vault.models import Password, Note, Address, PaymentCard, BankAccount

from vault.forms import (
	PasswordForm, 
	NoteForm,
	AddressForm,
	PaymentCardForm,
	BankAccountForm,
)

result = "Error"
message = "There was an error, please try again"

# Create your views here.
class AllItemsView(TemplateView):
	'''
	Generic TemplateView to display all items page
	'''
	template_name = "vault/all-items.html"

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["passwords"] = Password.objects.filter(user=self.request.user)
		context["notes"] = Note.objects.filter(user=self.request.user)
		context["addresses"] = Address.objects.filter(user=self.request.user)
		context["payment_cards"] = PaymentCard.objects.filter(user=self.request.user)
		context["bank_accounts"] = BankAccount.objects.filter(user=self.request.user)
		return context	


class PasswordsView(TemplateView):
	'''
	Generic TemplateView to display passwords page
	'''
	template_name = "vault/passwords.html"

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["passwords"] = Password.objects.filter(user=self.request.user)
		return context	


class CreatePasswordView(AjaxFormMixin, FormView):
	'''
	Generic FormView with our mixin for password creation
	'''

	template_name = "vault/create_item.html"
	form_class = PasswordForm
	success_url = "/"

	result = "Success"
	message = "Your password has been created successfully."

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["item_name"] = "password"
		context["item_form_id"] = "passwordform"
		context["action_url"] = "/vault/create/password"
		return context		


class DetailPasswordView(DetailView):
	'''
	Generic DetailView to display details of a password.
	'''

	model = Password
	template_name = 'vault/detail_item.html'
	context_object_name = 'password'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['password'] = Password.objects.get(id=self.kwargs.get('pk'))

		return context


class UpdatePasswordView(UpdateView):
    '''
    Generic UpdateView to edit a password.
    '''

    model = Password
    fields = ['url', 'name', 'email', 'password']
    template_name = 'vault/create_item.html'
    success_url = "/vault/passwords"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["item_name"] = "password"
        context["update"] = True
    
        return context	


class DeletePasswordView(DeleteView):
    '''
    Generic DeleteView to delete a password.
    '''
    model = Password
    success_url ="/vault/passwords"
    template_name = "vault/delete_item.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["item"] = "password"
    
        return context	


class NotesView(TemplateView):
	'''
	Generic TemplateView to display notes page
	'''
	template_name = "vault/notes.html"

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["notes"] = Note.objects.filter(user=self.request.user)
		return context	


class CreateNoteView(AjaxFormMixin, FormView):
	'''
	Generic FormView with our mixin for note creation
	'''

	template_name = "vault/create_item.html"
	form_class = NoteForm
	success_url = "/"

	result = "Success"
	message = "Your note has been created successfully."


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["item_name"] = "note"
		context["item_form_id"] = "noteform"
		context["action_url"] = "/vault/create/note"
		return context		


class DetailNoteView(DetailView):
	'''
	Generic DetailView to display details of a note.
	'''

	model = Note
	template_name = 'vault/detail_item.html'
	context_object_name = 'note'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['note'] = Note.objects.get(id=self.kwargs.get('pk'))

		return context


class UpdateNoteView(UpdateView):
    '''
    Generic UpdateView to edit a note.
    '''

    model = Note
    fields = ['name', 'body']
    template_name = 'vault/create_item.html'
    success_url = "/vault/notes"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["item_name"] = "note"
        context["update"] = True
    
        return context	


class DeleteNoteView(DeleteView):
    '''
    Generic DeleteView to delete a note.
    '''
    model = Note
    success_url ="/vault/notes"
    template_name = "vault/delete_item.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["item"] = "note"
    
        return context	


class AddressesView(TemplateView):
	'''
	Generic TemplateView to display addresses page
	'''
	template_name = "vault/addresses.html"

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["addresses"] = Address.objects.filter(user=self.request.user)
		return context	


class CreateAddressView(AjaxFormMixin, FormView):
	'''
	Generic FormView with our mixin for address creation
	'''

	template_name = "vault/create_item.html"
	form_class = AddressForm
	success_url = "/"

	result = "Success"
	message = "Your address has been created successfully."

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["item_name"] = "address"
		context["item_form_id"] = "addressform"
		context["action_url"] = "/vault/create/address"
		return context		


class DetailAddressView(DetailView):
	'''
	Generic DetailView to display details of an address.
	'''

	model = Address
	template_name = 'vault/detail_item.html'
	context_object_name = 'address'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['address'] = Address.objects.get(id=self.kwargs.get('pk'))

		return context


class UpdateAddressView(UpdateView):
    '''
    Generic UpdateView to edit an address.
    '''

    model = Address
    fields = ['name', 'title', 'first_name', 'middle_name','last_name', 
            'gender', 'birthday', 'address1', 'address2', 'address3', 'city', 
            'county', 'state', 'zip', 'country', 'email', 'phone']
    template_name = 'vault/create_item.html'
    success_url = "/vault/addresses"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["item_name"] = "address"
        context["update"] = True
    
        return context	



class DeleteAddressView(DeleteView):
    '''
    Generic DeleteView to delete an address.
    '''
    model = Address
    success_url ="/vault/addresses"
    template_name = "vault/delete_item.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["item"] = "address"
    
        return context	



class PaymentCardsView(TemplateView):
	'''
	Generic TemplateView to display payment cards page
	'''
	template_name = "vault/payment_cards.html"

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["payment_cards"] = PaymentCard.objects.filter(user=self.request.user)
		return context	


class CreatePaymentCardView(AjaxFormMixin, FormView):
	'''
	Generic FormView with our mixin for payment card creation
	'''

	template_name = "vault/create_item.html"
	form_class = PaymentCardForm
	success_url = "/"

	result = "Success"
	message = "Your payment card has been created successfully."

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["item_name"] = "payment card"
		context["item_form_id"] = "paymentcardform"
		context["action_url"] = "/vault/create/payment-card"
		return context		

class DetailPaymentCardView(DetailView):
	'''
	Generic DetailView to display details of a payment card.
	'''

	model = PaymentCard
	template_name = 'vault/detail_item.html'
	context_object_name = 'payment_card'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['payment_card'] = PaymentCard.objects.get(id=self.kwargs.get('pk'))

		return context


class UpdatePaymentCardView(UpdateView):
    '''
    Generic UpdateView to edit a payment card.
    '''

    model = PaymentCard
    fields = ['name', 'name_on_card', 'type', 'number', 'security_code', 'start_date', 'expiration_date']
    template_name = 'vault/create_item.html'
    success_url = "/vault/payment-cards"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["item_name"] = "payment card"
        context["update"] = True
    
        return context	



class DeletePaymentCardView(DeleteView):
    '''

templates/vault/addresses.html
{% extends 'base.html' %}
{% load static %}

{% block extend_head %}

    <title>Addresses</title>

{% endblock %}

{% block content %}

  <h2 class="header" style="background-color: rgb(114, 255, 0);">Addresses</h3>

  <div class="container">
    
    <h4>Addresses <a href="{% url 'vault:create_address' %}"><img class="add-icon" src="{% static 'img/add-icon.png' %}" alt=""></a></h4>
    {% if addresses %}

      <div class="cards-container">

        {% for address in addresses %}

            <div class="card" id="address-card" style="width: 18rem; margin: 10px;">
                <div class="card-img-container" id="address-cap">
                    <img class="card-img-top" src="{% static 'img/address.png' %}" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{  address.name }}</h5>
                </div>
                <div class="card-body">
                    <div class="card-link-container">
                        <a href="{% url 'vault:detail_address' address.id %}" class="link-container card-view-btn card-link">View</a>
                        <a href="{% url 'vault:update_address' address.id %}" class="link-container card-edit-btn card-link">Edit</a>
                        <a href="{% url 'vault:delete_address' address.id %}" class="link-container card-delete-btn card-link">Delete</a>
                    </div>
                </div>
            </div>

        {% endfor %}
    
      </div>

    {% else %}
        <p>You have not registered addresses</p>
    {% endif %}

  </div>

{% endblock %}

{% block extend_footer %}
    <script type="text/javascript">

        let hoveredSrc = "{% static 'img/add-icon-hovered.png' %}";
        let unhoveredSrc = "{% static 'img/add-icon.png' %}";

    </script>

    <script type="text/javascript" src="{% static 'toggle_add_icon.js' %}"></script>
{% endblock %}

templates/vault/all-items.html
{% extends 'base.html' %}
{% load static %}

{% block extend_head %}

    <title>All Items</title>

{% endblock %}

{% block content %}

  <h2 class="header">All Items</h3>

  <div class="container">
    
    <h4>Passwords <a href="{% url 'vault:create_password' %}"><img class="add-icon" src="{% static 'img/add-icon.png' %}" alt="Plus icon"></a></h4>
    {% if passwords %}
    
        <div class="cards-container">
            {% for password in passwords %}

                <div class="card" id="password-card" style="width: 18rem; margin: 10px;">
                    <div class="card-img-container" id="password-cap">
                        <img class="card-img-top" src="{% static 'img/password.png' %}" alt="Card image cap">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{  password.name }}</h5>
                    </div>
                    <div class="card-body">
                        <div class="card-link-container">
                            <a href="{% url 'vault:detail_password' password.id %}" class="link-container card-view-btn card-link">View</a>
                            <a href="{% url 'vault:update_password' password.id %}" class="link-container card-edit-btn card-link">Edit</a>
                            <a href="{% url 'vault:delete_password' password.id %}" class="link-container card-delete-btn card-link">Delete</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div> 

    {% else %}
        <p>You have not registered passwords</p>
    {% endif %}


    <h4>Notes <a href="{% url 'vault:create_note' %}"><img class="add-icon" src="{% static 'img/add-icon.png' %}" alt=""></a></h4>

    
    {% if notes %}

        <div class="cards-container">

            {% for note in notes %}

                <div class="card" id="note-card" style="width: 18rem; margin: 10px;">
                    <div class="card-img-container" id="note-cap">
                        <img class="card-img-top" src="{% static 'img/note.png' %}" alt="Card image cap">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{  note.name }}</h5>
                    </div>
                    <div class="card-body">
                        <div class="card-link-container">
                            <a href="{% url 'vault:detail_note' note.id %}" class="link-container card-view-btn card-link">View</a>
                            <a href="{% url 'vault:update_note' note.id %}" class="link-container card-edit-btn card-link">Edit</a>
                            <a href="{% url 'vault:delete_note' note.id %}" class="link-container card-delete-btn card-link">Delete</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        
        </div>

    {% else %}
        <p>You have not registered notes</p>
    {% endif %}


    <h4>Addresses <a href="{% url 'vault:create_address' %}"><img class="add-icon" src="{% static 'img/add-icon.png' %}" alt=""></a></h4>
    {% if addresses %}

        <div class="cards-container">

            {% for address in addresses %}

                <div class="card" id="address-card" style="width: 18rem; margin: 10px;">
                    <div class="card-img-container" id="address-cap">
                        <img class="card-img-top" src="{% static 'img/address.png' %}" alt="Card image cap">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{  address.name }}</h5>
                    </div>
                    <div class="card-body">
                        <div class="card-link-container">
                            <a href="{% url 'vault:detail_address' address.id %}" class="link-container card-view-btn card-link">View</a>
                            <a href="{% url 'vault:update_address' address.id %}" class="link-container card-edit-btn card-link">Edit</a>
                            <a href="{% url 'vault:delete_address' address.id %}" class="link-container card-delete-btn card-link">Delete</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        
        </div>

    {% else %}
        <p>You have not registered addresses</p>
    {% endif %}


    <h4>Payment Cards <a href="{% url 'vault:create_payment_card' %}"><img class="add-icon" src="{% static 'img/add-icon.png' %}" alt=""></a></h4>
    {% if payment_cards %}

        <div class="cards-container">

            {% for payment_card in payment_cards %}

                <div class="card" id="payment-card-card" style="width: 18rem; margin: 10px;">
                    <div class="card-img-container" id="payment-card-cap">
                        <img class="card-img-top" src="{% static 'img/payment_card.png' %}" alt="Card image cap">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{  payment_card.name }}</h5>
                    </div>
                    <div class="card-body">
                        <div class="card-link-container">
                            <a href="{% url 'vault:detail_payment_card' payment_card.id %}" class="link-container card-view-btn card-link">View</a>
                            <a href="{% url 'vault:update_payment_card' payment_card.id %}" class="link-container card-edit-btn card-link">Edit</a>
                            <a href="{% url 'vault:delete_payment_card' payment_card.id %}" class="link-container card-delete-btn card-link">Delete</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        
        </div>

    {% else %}
        <p>You have not registered payment cards</p>
    {% endif %}


    <h4>Bank Accounts <a href="{% url 'vault:create_bank_account' %}"><img class="add-icon" src="{% static 'img/add-icon.png' %}" alt=""></a></h4>
    {% if bank_accounts %}
        
        <div class="cards-container">

            {% for bank_account in bank_accounts %}

                <div class="card" id="bank-account-card" style="width: 18rem; margin: 10px;">
                    <div class="card-img-container" id="bank-account-cap">
                        <img class="card-img-top" src="{% static 'img/bank-account.png' %}" alt="Card image cap">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{  bank_account.name }}</h5>
                    </div>
                    <div class="card-body">
                        <div class="card-link-container">
                            <a href="{% url 'vault:detail_bank_account' bank_account.id %}" class="link-container card-view-btn card-link">View</a>
                            <a href="{% url 'vault:update_bank_account' bank_account.id %}" class="link-container card-edit-btn card-link">Edit</a>
                            <a href="{% url 'vault:delete_bank_account' bank_account.id %}" class="link-container card-delete-btn card-link">Delete</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        
        </div>

    {% else %}
        <p>You have not registered bank accounts</p>
    {% endif %}


  </div>

{% endblock %}

{% block extend_footer %}
    <script type="text/javascript">

        let hoveredSrc = "{% static 'img/add-icon-hovered.png' %}";
        let unhoveredSrc = "{% static 'img/add-icon.png' %}";

    </script>

    <script type="text/javascript" src="{% static 'toggle_add_icon.js' %}"></script>
{% endblock %}

templates/vault/bank_accounts.html
{% extends 'base.html' %}
{% load static %}

{% block extend_head %}

    <title>Bank Accounts</title>

{% endblock %}

{% block content %}

  <h2 class="header" style="background-color: rgb(234, 71, 255);">Bank Accounts</h3>

  <div class="container">
    
    <h4>Bank Accounts <a href="{% url 'vault:create_bank_account' %}"><img class="add-icon" src="{% static 'img/add-icon.png' %}" alt=""></a></h4>
    {% if bank_accounts %}

      <div class="cards-container">

        {% for bank_account in bank_accounts %}

            <div class="card" id="bank-account-card" style="width: 18rem; margin: 10px;">
                <div class="card-img-container" id="bank-account-cap">
                    <img class="card-img-top" src="{% static 'img/bank-account.png' %}" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{  bank_account.name }}</h5>
                </div>
                <div class="card-body">
                    <div class="card-link-container">
                        <a href="{% url 'vault:detail_bank_account' bank_account.id %}" class="link-container card-view-btn card-link">View</a>
                        <a href="{% url 'vault:update_bank_account' bank_account.id %}" class="link-container card-edit-btn card-link">Edit</a>
                        <a href="{% url 'vault:delete_bank_account' bank_account.id %}" class="link-container card-delete-btn card-link">Delete</a>
                    </div>
                </div>
            </div>

        {% endfor %}
    
      </div>

    {% else %}
        <p>You have not registered bank accounts</p>
    {% endif %}

  </div>

{% endblock %}

{% block extend_footer %}
    <script type="text/javascript">

        let hoveredSrc = "{% static 'img/add-icon-hovered.png' %}";
        let unhoveredSrc = "{% static 'img/add-icon.png' %}";

    </script>

    <script type="text/javascript" src="{% static 'toggle_add_icon.js' %}"></script>
{% endblock %}

templates/vault/delete_item.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}

    <title>Delete {{ item }}</title>

{% endblock %}


{% block content %}

    {% if item == "password" %}

        <h2 class="header" style="background-color: tomato;">Delete {{ item }}</h3>

    {% elif item == "note" %}

        <h2 class="header" style="background-color: rgb(255, 237, 0);">Delete {{ item }}</h3>

    {% elif item == "address" %}

        <h2 class="header" style="background-color: rgb(114, 255, 0);">Delete {{ item }}</h3>

    {% elif item == "payment card" %}

        <h2 class="header" style="background-color: rgb(74, 71, 255);">Delete {{ item }}</h3>

    {% elif item == "bank account" %}

        <h2 class="header" style="background-color: rgb(234, 71, 255);">Delete {{ item }}</h3>

    {% endif %}

    <section class="position-relative py-4 py-xl-5">
        <div id="delete-container" class="container position-relative">
            <h5 class="text-center mb-4">Are you sure you want to delete the {{ item }} called "{{ object.name }}"?</h5>
            <form method="post">
                {% csrf_token %}
                <div style="text-align: center;">
                    <div style="width: 35%;display: inline-block;"><button id="yes-delete-btn" class="btn btn-primary d-block w-100 confirm-delete-btn" type="submit" style="display: inline;margin-right: 10px;background: rgb(27,157,80);border-color: rgb(27,157,80);">Yes</button></div>
                    
                    <div style="width: 35%;display: inline-block;">
                    
                        {% if item == "password" %}

                            <a href="{% url 'vault:passwords' %}"><button id="no-delete-btn" class="btn btn-primary d-block w-100 confirm-delete-btn" type="button" style="display: inline;margin: auto;margin-left: 10px;background: rgb(197,12,12);border-color: rgb(197,12,12);">No</button></a>
                    
                        {% elif item == "note" %}
                    
                            <a href="{% url 'vault:notes' %}"><button id="no-delete-btn" class="btn btn-primary d-block w-100 confirm-delete-btn" type="button" style="display: inline;margin: auto;margin-left: 10px;background: rgb(197,12,12);border-color: rgb(197,12,12);">No</button></a>
                    
                        {% elif item == "address" %}
                    
                            <a href="{% url 'vault:addresses' %}"><button id="no-delete-btn" class="btn btn-primary d-block w-100 confirm-delete-btn" type="button" style="display: inline;margin: auto;margin-left: 10px;background: rgb(197,12,12);border-color: rgb(197,12,12);">No</button></a>
                    
                        {% elif item == "payment card" %}
                    
                            <a href="{% url 'vault:payment-cards' %}"><button id="no-delete-btn" class="btn btn-primary d-block w-100 confirm-delete-btn" type="button" style="display: inline;margin: auto;margin-left: 10px;background: rgb(197,12,12);border-color: rgb(197,12,12);">No</button></a>
                        
                        {% elif item == "bank account" %}
                    
                            <a href="{% url 'vault:bank-accounts' %}"><button id="no-delete-btn" class="btn btn-primary d-block w-100 confirm-delete-btn" type="button" style="display: inline;margin: auto;margin-left: 10px;background: rgb(197,12,12);border-color: rgb(197,12,12);">No</button></a>
                    
                        {% endif %}
                    
                    </div>
                    
                </div>
            </form>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}


{% block extend_footer %}

{% endblock %}